db:
  host:     "localhost"
  port:     "5040"
  username: "mobile"
  password: "password"
  dbname:   "profilesdb"
  sslmode:  "disable"

http_server:
  address: "localhost:8080"
  timeout: 4s
  ctx_timeout: 60s
  idle_timeout: 60s
api:
  age_url: https://api.agify.io
  gender_url: https://api.genderize.io
  nationality_url: https://api.nationalize.io